project:
  name: ${ProjectName}
  regions:
    - us-east-1
  s3_bucket: ${ProjectName}-codepipeline-bucket

tests:
  mytest:
    template: ./module/parent_stack.yaml
    parameters:
      BucketName: ${ProjectName}-codepipeline-bucket # Reference the first parameter from env.json
      ProjectName: ${ProjectName} # Reference the second parameter from env.json
