project:
  name: !Sub "${ProjectName}"
  regions:
    - us-east-1
  s3_bucket: !Sub "${ProjectName}-codepipeline-bucket"

tests:
  mytest:
    template: ./module/parent_stack.yaml
    parameters:
      BucketName: !Sub "${ProjectName}-codepipeline-bucket"
      ProjectName: !Sub "${ProjectName}"
