AWSTemplateFormatVersion: "2010-09-09"

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyCodePipeline
      # RoleArn: arn:aws:iam::ACCOUNT_ID:role/AWSCodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: lab2-21522490-bucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: "HongQuan1812"
                Repo: "DevOps_learning"
                Branch: "main"
                OAuthToken: !Ref GitHubOAuthToken
        - Name: Build
          Actions:
            - Name: CodeBuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: MyCodeBuildProject
        # - Name: Deploy
        #   Actions:
        #     - Name: CloudFormationDeploy
        #       ActionTypeId:
        #         Category: Deploy
        #         Owner: AWS
        #         Provider: CloudFormation
        #         Version: 1
        #       InputArtifacts:
        #         - Name: BuildOutput
        #       Configuration:
        #         StackName: lab2-21522490-stack
        #         ActionMode: CREATE_UPDATE
        #         TemplatePath: BuildOutput::cloudformation-template.yaml
