version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install cfn-lint taskcat

  pre_build:
    commands:
      - echo Running cfn-lint on all CloudFormation templates...
      - cd NT548_LAB/lab2/CLoudformation
      - for template in module/*.yaml; do
        echo "Linting $template...";
        cfn-lint --template $template;
        done

  build:
    commands:
      - echo Running taskcat tests...
      - scripts/run_taskcat.sh

artifacts:
  files:
    - "**/*"
  discard-paths: yes
