version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install cfn-lint taskcat

  pre_build:
    commands:
      - echo Running cfn-lint on all CloudFormation templates...
      - cd NT548_LAB/lab2/CLoudformation
      - for template in module/*.yaml; do
        echo "Linting $template...";
        cfn-lint --template $template;
        done

  build:
    commands:
      - echo Running taskcat tests...
      - taskcat test run

  post_build:
    commands:
      - echo Taskcat tests completed. You can add CloudFormation deploy here if required.

      - BucketName=lab2-21522490-codepipeline-bucket
      - ProjectName=lab2-21522490-module

      - for template in module/*.yaml; do
        aws s3 cp $template s3://$BucketName/$ProjectName/$template;
        done

artifacts:
  files:
    - "**/*"
  discard-paths: yes
