version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install cfn-lint taskcat

  pre_build:
    commands:
      - echo Running cfn-lint on CloudFormation templates...
      - cd NT548_LAB/lab2/CLoudformation
      - cfn-lint --template ./module/parent_stack.yaml
      - cfn-lint --template ./module/vpc.yaml
      - cfn-lint --template ./module/sg.yaml
      - cfn-lint --template ./module/ec2.yaml
      - cfn-lint --template ./module/nat_gateway.yaml
      - cfn-lint --template ./module/route_table.yaml
      - scripts/create_bucket.sh lab2-21522490-bucket

  build:
    commands:
      - echo Running taskcat tests...
      - taskcat test run

artifacts:
  files:
    - "**/*"
  discard-paths: yes
