AWSTemplateFormatVersion: "2010-09-09"

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lab2-21522490-codepipeline-bucket # Ensure this bucket name is unique globally

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "lab2-21522490-project"
      ServiceRole: arn:aws:iam::605134471711:role/CodeBuild
      Source:
        Type: CODEPIPELINE
        BuildSpec: "NT548_LAB/lab2/CLoudformation/CI-CD/buildspec.yml"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"
        Type: "LINUX_CONTAINER"
      TimeoutInMinutes: 30

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: lab2-21522490-pipeline
      RoleArn: arn:aws:iam::605134471711:role/service-role/Codepipeline # Ensure this is the correct role ARN
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: arn:aws:codeconnections:us-east-1:605134471711:connection/6ef2845e-cbba-48c2-bb82-1cd156deb6a1
                FullRepositoryId: HongQuan1812/DevOps_learning # Your GitHub repository
                BranchName: main # Branch to pull code from
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject # Ensure the CodeBuild project exists
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: CloudFormationDeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                StackName: "lab2-21522490-pipeline-deploystage"
                RoleArn: arn:aws:iam::605134471711:role/CloudFormation # Replace with the appropriate role ARN
                ActionMode: "CREATE_UPDATE"
                Capabilities: "CAPABILITY_NAMED_IAM"
                TemplatePath: SourceOutput::NT548_LAB/lab2/CLoudformation/module/parent_stack.yaml
                ParameterOverrides: |
                  BucketName=lab2-21522490-codepipeline-bucket
                  ProjectName=lab2-21522490-module
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket

Outputs:
  PipelineId:
    Value: !Ref CodePipeline
    Description: "The ID of the created pipeline"

  ArtifactBucket:
    Value: !Ref ArtifactBucket
